### PR TITLE
Cache readerat

### PR DESCRIPTION
**Pull request by vcaputo**

### CODE REVIEW

**Comment by mischief** [comment]
@vcaputo if ReadAt cannot get the whole range, i believe it should just return a short read.

**Comment by vcaputo** [comment]
@mischief from the io package docs for ReadAt:
>     When ReadAt returns n < len(p), it returns a non-nil error explaining
    why more bytes were not returned. In this respect, ReadAt is stricter
    than Read.

**Comment by mischief** [comment]
@vcaputo are the other PRs defunct?

**Comment by mischief** [comment]
seems so. closing them and merging this one. thanks.

**Pull request merged**
